/*
 * Creative Commons - Attribution, Share Alike 4.0 
 * Nullpointer Works (2020)
 * Use is subject to license terms.
 */
package com.nullpointerworks.j2d.shader;

import com.nullpointerworks.core.buffer.IntBuffer;

/**
 * The engine performs various calculations before rendering takes place. This object is an intermediate step between requesting, layering and rendering.
 * @since 1.0.0
 */
public class BufferedRequest 
{
	/**
	 * The reference image to render.
	 * @since 1.0.0
	 */
	public IntBuffer image = null;
	
	/**
	 * The transformation matrix generated by the {@code Transform} shader.
	 * @since 1.0.0
	 */
	public float[][] transform = null;
	
	/**
	 * The rendering depth used by the {@code Layering} shader to determine pixel obfuscation.
	 * @since 1.0.0
	 */
	public int layer = 1;
	
	/**
	 * Most left location of the rendering box used in the {@code Rasterizer} shader.
	 * @since 1.0.0
	 */
	public float x = 0f;
	
	/**
	 * Most up location of the rendering box used in the {@code Rasterizer} shader.
	 * @since 1.0.0
	 */
	public float y = 0f;
	
	/**
	 * Total width of the rendering box used in the {@code Rasterizer} shader.
	 * @since 1.0.0
	 */
	public float w = 0f;
	
	/**
	 * Total height of the rendering box used in the {@code Rasterizer} shader.
	 * @since 1.0.0
	 */
	public float h = 0f;
	
	/**
	 * Free object references for garbage collection.
	 * @since 1.0.0
	 */
	public void free()
	{
		image		= null;
		transform 	= null;
	}
}
